# Perceptron Single Step Update

Now you will implement the single step update for the perceptron algorithm (implemented with  0−1  loss). You will be given the feature vector as an array of numbers, the current  θ  and  θ0  parameters, and the correct label of the feature vector. The function should return a tuple in which the first element is the correctly updated value of  θ  and the second element is the correctly updated value of  θ0 .

Available Functions: You have access to the NumPy python library as np.

Tip:: Because of numerical instabilities, it is preferable to identify  0  with a small range  [−ε,ε] . That is, when  x  is a float, “ x=0 " should be checked with  |x|<ε .

In [128]:
#Defined Function
def perceptron_single_step_update(feature_vector,label,current_theta, current_theta_0):
    if (label*(np.dot(feature_vector, current_theta) + current_theta_0)) <= 0:
        current_theta= current_theta + (np.dot(label, feature_vector))
        current_theta_0= (current_theta_0 + label)
    else:
        current_theta_0= current_theta_0
        current_theta= current_theta
    return (current_theta, current_theta_0)

##Example
feature_vector= np.array([-0.45857273, -0.33374714,  0.0101883,   0.06653433, -0.03850377, -0.32448486,
 -0.36190903, -0.48311127, -0.47592383, -0.24156544])

label= -1
current_theta=  np.array([-0.3525065,   0.14089595, -0.38289749, -0.22981247, -0.1796229,  -0.35851499,
  0.19970475,  0.22760155,  0.39383912,  0.4002642])
current_theta_0= -0.731389098744194

perceptron_single_step_update(feature_vector,label,current_theta, current_theta_0)

(array([-0.3525065 ,  0.14089595, -0.38289749, -0.22981247, -0.1796229 ,
        -0.35851499,  0.19970475,  0.22760155,  0.39383912,  0.4002642 ]),
 -0.731389098744194)

# Full Perceptron Algorithm
In this step you will implement the full perceptron algorithm. You will be given the same feature matrix and labels array as you were given in The Complete Hinge Loss. You will also be given  T , the maximum number of times that you should iterate through the feature matrix before terminating the algorithm. Initialize  θ  and  θ0  to zero. This function should return a tuple in which the first element is the final value of  θ  and the second element is the value of  θ0 .

Tip: Call the function perceptron_single_step_update directly without coding it again.

Hint: Make sure you initialize theta to a 1D array of shape (n,) and not a 2D array of shape (1, n).

Note: Please call get_order(feature_matrix.shape[0]), and use the ordering to iterate the feature matrix in each iteration. The ordering is specified due to grading purpose. In practice, people typically just randomly shuffle indices to do stochastic optimization.

Available Functions: You have access to the NumPy python library as np and perceptron_single_step_update which you have already implemented.

In [327]:
##Function used instructed by  the exercise.. craaazy stuff bro 
from string import punctuation, digits
import numpy as np
import random
from matplotlib import pyplot as plt
%matplotlib inline

def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indices = list(range(n_samples))
        random.shuffle(indices)
        return indices

In [354]:
def perceptron(feature_matrix, labels, T):
    theta_0  = 0
    theta= np.zeros(len(feature_matrix[0])) 
    for epoch in range(T): 
        for i in get_order(feature_matrix.shape[0]):
            if (labels[i]*(np.dot(feature_matrix[i], theta) + theta_0)) <= 0:
                theta= theta + (np.dot(labels[i], feature_matrix[i]))
                theta_0= (theta_0 + labels[i])
            else:
                theta_0= theta_0
                theta= theta
    return((theta, theta_0))

In [355]:
#Example
feature_matrix= np.array([
    [-1.85954975e-01, -5.09014576e-02,  3.18341925e-01, -4.92494361e-01, 1.17290142e-01],
    [-2.67159545e-01, 1.58003187e-01, -3.07128547e-01, 1.52733302e-01, -9.28785729e-02],
    [-1.68852441e-01,  2.13241036e-01,  1.05168850e-01,  3.86352473e-02, 8.45188135e-02],
    [-3.27003047e-01,  4.30601481e-01, -3.22000933e-02, -2.95024675e-01, 1.05874501e-01], 
    [9.11263652e-02, -4.07725654e-01,  4.85931682e-02, -3.60755570e-01, 2.86148788e-02],
    [-3.74836722e-01,  2.37854783e-01,  2.64549662e-01, -1.40486303e-01, -3.52008461e-01],
    [-5.07496929e-02,  3.09763446e-01, -1.81890428e-01,  2.16650758e-01, 1.52858451e-01],
    [1.30719418e-01, -2.57653578e-01, -4.92338668e-01,  4.50303583e-01, -1.06309065e-01],
    [4.34751868e-01,  1.82111419e-02,  3.76404633e-01,  2.93951357e-01, 3.13608230e-01],
    [1.48316020e-01,  3.95543188e-04, -3.14938610e-01,  4.55522298e-01, -1.66514414e-01]])
labels= np.array([-1,  1 , 1 ,-1 ,-1 , 1 ,-1 ,-1 , 1 , 1])
T= 5
perceptron(feature_matrix, labels, T)

(array([-0.15387717,  0.59725865,  1.49140252,  1.56823787, -1.51771519]), 1)

In [370]:
def perceptron(feature_matrix, labels, T):
    current_theta_0  = 0
    current_theta= np.zeros(len(feature_matrix[0]))
    for epoch in range(T): 
        for i in get_order(feature_matrix.shape[0]):
            if (labels[i]*(np.dot(feature_matrix[i], current_theta) + current_theta_0)) <= 0:
                current_theta= current_theta + (np.dot(labels[i], feature_matrix[i]))
                current_theta_0= (current_theta_0 + labels[i])
            else:
                current_theta= current_theta
                current_theta_0 = current_theta_0
    return((current_theta, current_theta_0))

In [371]:
perceptron(feature_matrix, labels, T)

(array([-0.15387717,  0.59725865,  1.49140252,  1.56823787, -1.51771519]), 1)